name: Node.js CI

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: |
        docker build -t salmagaddour/my-app:v1.0 .
      working-directory: https://hub.docker.com/layers/salmagaddour/my-app/v1.0

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_SALMAGADDOUR }} --password-stdin
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_SALMAGADDOUR }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push salmagaddour/my-app:v1.0
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Change this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
